### PR TITLE
update pf1 support

### LINKED ISSUE #643: [BUG] - [Pathfinder 1e] - Incorrect localization keys for currencies
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Pathfinder 1e v10 has changed the localization keys so the older ones don't display correctly.

> **Solution**: The new keys are `PF1.Currency.Full.pp` for _platin_,  `PF1.Currency.Full.gp` for _gold_
> `PF1.Currency.Full.sp` for _silver_ and `PF1.Currency.Full.cp` for _copper_.

**To Reproduce**

1. Create any kind of PC or NPC actor
2. Add currencies
3. Convert to any kind of item piles object
5. See error

**Expected behavior**
It is expected for the i18n key to display the name of the currency instead of the key itself.

**Screenshots**

imagen

**Setup:**

- Foundry Version: 11.315
- System Version: Pathfinder v10.7
- Item Piles Version: latest (I think 3.1.0)
- Browser & version: Foundry app itself (I believe is Electron)

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
This worked for **Pathfinder 1e v9.6** so maximum version needs to be updated.

### PR DESCRIPTION
**Pull request by mkahvi**
Changes:
- Alters cost transformer to be more sane
  - This increases minimum PF1 version to v10.0
    - Added old config for v9.x
- Adds more similarity data points
- Disallows stacking containers which don't support it
- Fixes invalid item type configuration
- Updates i18n keys

Fixes #643

### CODE REVIEW

**Comment by Haxxer** [comment]
You can take a look at d&d5e's files to see how system versions are handled

**Comment by mkahvi** [comment]
@Haxxer I set it up, but I'm not quite convinced it's correct. The version number for the old is the last version the config is valid for I take? Otherwise I don't see how the latest config version would be used for v10 and all its subversions.

Besides that point and inability to test fully due to #642, this should be ready.

**Comment by Haxxer** [comment]
That's correct, it's the last compatible version, so for D&D5e, that was 2.4.1 before the jump to 3.1.2, meaning that all versions between 2.4.1>3.1.2 are only compatible with 3.1.2

**Comment by Haxxer** [comment]
05ccc19 should fix your issue

**Comment by mkahvi** [comment]
I can confirm the fix is working and that everything looks to be in working order with this as such.

**Pull request merged**
