### PR TITLE
Vaarfeu system

### PR DESCRIPTION
**Pull request by iwontgiveyoumyname**
Added Vaarfeu system.
(the link will send to an error, this is a private system I created, sorry for the double requests, I'm kinda new to github)

### CODE REVIEW

**Comment by Haxxer** [comment]
If it's a private system, why submit to this github repo? You can download the code and compile it yourself.

**Comment by iwontgiveyoumyname** [comment]
But with each update of Itempiles I would have to reajust the code no?

**Comment by Haxxer** [comment]
It doesn't matter to me, it's just confusion why a very public module needs to support a private and personal system haha - I'll merge it in the next update

**Comment by iwontgiveyoumyname** [comment]
Thanks for that!

**Pull request merged**
