### PR TITLE
Update for french PR.

### PR DESCRIPTION
**Pull request by Padhiver**
Update for french PR.

### CODE REVIEW

**Comment by Haxxer** [comment]
Could you please use the other pull request to put this in?

**Comment by Padhiver** [comment]
Oh sorry, I didn't know you could PR more than one file at a time, I think it's ok this time?

**Comment by Haxxer** [comment]
Thank you for your contribution!

**Comment by Haxxer** [comment]
@Padhiver Would you mind translating these two too? :)

```
"LinkedActorWarning": {
    "Title": "Item Piles & Linked Actor",
    "Content": "Are you sure you want to turn this <strong>linked actor</strong> into an item pile? This actor's token is linked and all tokens of this actor will share its inventory and attributes."
},
"NoSystemFound": {
    "Title": "System Not Recognized",
    "Content": "This system is not currently fully supported. This means that the module does not know how to best handle this system's items, but can still operate in a limited fashion.<br><br>You can configure the module's settings yourself, but it requires a bit of technical know-how.<br><br>If you have any questions, ping <strong>Wasp#2005</strong> on the Foundry discord."
},
"SystemFound": {
    "Title": "System Recognized",
    "Content": "This system was previously not supported, but in an recent update it was added as a supported system!<br><br>Do you want to load this system's default Item Pile settings?",
    "Confirm": "Apply System Defaults"
},
```

I fixed some issues and added some extra features to make sure things aren't breaking too much

**Comment by Padhiver** [comment]
> Je viens justement de finir la traduction du module et je vois que tu as été plus rapide de 20 minutes haha. Bien joué ! Même si je dois avouer que je suis vert

Ahah désolé, hésite pas à review, j'ai eu du mal avec certain terme !

**Pull request merged**
